inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  DisplayStyleGuide: true
  ExtraDetails: true

# https://github.com/jamesmartin/inline_svg/pull/171/files#r1798763446
Style/EachWithObject:
  Enabled: false

# https://github.com/jamesmartin/inline_svg/pull/177#issuecomment-2530239552
RSpec/DescribedClass:
  EnforcedStyle: explicit
